env:
  browser: true
  es2021: true
  node: true
extends: airbnb-base
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules:
  no-console: 0
  max-len: 0
  no-restricted-syntax: 0
  quote-props: 0
  quotes: 0
  no-else-return: 0
  import/extensions:
    - error
    - ignorePackages
    - js: always
  no-underscore-dangle: [2, {'allow': ['__filename', '__dirname']}]
